name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleCoreDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: novadial-core-debug-apk
          path: app/build/outputs/apk/core/debug/phone-29-core-debug.apk
